In [2]:
import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import timedelta
from scipy.stats import ks_2samp
from datetime import datetime, time
import os

In [ ]:
chemin24 = "fichiersexceluniformises/2024"

May24 = pd.read_excel(os.path.join(chemin24, '5.xlsx'))
Jun24 = pd.read_excel(os.path.join(chemin24, '6.xlsx'))
Jul24 = pd.read_excel(os.path.join(chemin24, '7.xlsx'))
Aug24 = pd.read_excel(os.path.join(chemin24, '8.xlsx'))
Sep24 = pd.read_excel(os.path.join(chemin24, '9.xlsx'))
Oct24 = pd.read_excel(os.path.join(chemin24, '10.xlsx'))
Nov24 = pd.read_excel(os.path.join(chemin24, '11.xlsx'))
Dec24 = pd.read_excel(os.path.join(chemin24, '12.xlsx'))

In [221]:
chemin24 = "fichiersexceluniformises/2024"
May24 = pd.read_excel(os.path.join(chemin24, '5.xlsx'))
Jun24 = pd.read_excel(os.path.join(chemin24, '6.xlsx'))
Jul24 = pd.read_excel(os.path.join(chemin24, '7.xlsx'))
Aug24 = pd.read_excel(os.path.join(chemin24, '8.xlsx'))
Sep24 = pd.read_excel(os.path.join(chemin24, '9.xlsx'))

In [12]:

chemin24 = "fichierbrutsexcel/2024"
Apr24 = pd.read_excel(os.path.join(chemin24, '4.xlsx'))

In [13]:
Apr24

,Site,CP ID,Connector Type,Connector,Currency,Amount,Consum(kWh),Duration,Start
0,Fettes Avenue,UC25189,Rapid,1,Â£,10.99,19.99,00:30:53,2024-04-08 00:54:38
1,Dunoon 1 - Pier Car Park,61720,Rapid,1,Â£,4.86,17.99,00:23:42,2024-04-08 00:53:19
2,Fettes Avenue,UC25188,Rapid,1,Â£,1.04,1.88,00:19:48,2024-04-08 00:51:29
3,"Princes Street Charging Hub, Dundee",APT51423,Rapid,1,Â£,15.56,30.35,00:47:21,2024-04-08 00:51:08
4,"High Street, Ormiston",52993,AC,1,Â£,20.02,57.19,10:01:30,2024-04-08 00:49:38
...,...,...,...,...,...,...,...,...,...
129628,"Princes Street Charging Hub, Dundee",APT51423,Rapid,2,Â£,11.65,22.54,00:32:06,2024-04-29 01:48:24
129629,"Bankhead Depot, Bankhead Avenue, Edinburgh",51514,Rapid,2,Â£,1.85,3.37,00:18:17,2024-04-29 01:45:19
129630,Ingliston Park & Ride,FC15744,AC,2,Â£,0.00,0.48,10:58:55,2024-04-29 01:41:06
129631,"Kirkcaldy Railway Station Car Park, Whyte Melv...",APT50455,AC,1,Â£,5.46,25.74,05:28:56,2024-04-29 01:37:29
129632,"Princes Street Charging Hub, Dundee",APT51423,Rapid,2,Â£,6.25,11.74,00:17:44,2024-04-29 01:07:26

In [ ]:
# Sélectionner les colonnes que tu veux garder
cols_to_keep = ['CP ID','Amount','Consum(kWh)','Start','Duration']
Apr24=Apr24[cols_to_keep]

# Renommer les colonnes spécifiées
Apr24=Apr24.rename(columns={
'Consum(kWh)': 'Consumed(kWh)',
'CP ID ':'CPID'
})
Apr24

           CP ID  Amount  Consumed(kWh)               Start  Duration
0        UC25189   10.99          19.99 2024-04-08 00:54:38  00:30:53
1          61720    4.86          17.99 2024-04-08 00:53:19  00:23:42
2        UC25188    1.04           1.88 2024-04-08 00:51:29  00:19:48
3       APT51423   15.56          30.35 2024-04-08 00:51:08  00:47:21
4          52993   20.02          57.19 2024-04-08 00:49:38  10:01:30
...          ...     ...            ...                 ...       ...
129628  APT51423   11.65          22.54 2024-04-29 01:48:24  00:32:06
129629     51514    1.85           3.37 2024-04-29 01:45:19  00:18:17
129630   FC15744    0.00           0.48 2024-04-29 01:41:06  10:58:55
129631  APT50455    5.46          25.74 2024-04-29 01:37:29  05:28:56
129632  APT51423    6.25          11.74 2024-04-29 01:07:26  00:17:44

[129633 rows x 5 columns]

In [16]:
Apr24=Apr24.rename(columns={'CP ID':'CPID'})

In [17]:
Apr24.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129633 entries, 0 to 129632
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   CPID           129633 non-null  object
 1   Amount         129633 non-null  float64
 2   Consumed(kWh)  129632 non-null  float64
 3   Start          129633 non-null  datetime64[ns]
 4   Duration       129633 non-null  object
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 4.9+ MB

In [18]:

# Fonction de traitement
def analyser_dates(df, nom):
    df = df.copy()

    # Conversion CPID en string
    df['CPID'] = df['CPID'].astype(str)

    # Conversion de Start en datetime
    df['Start'] = pd.to_datetime(df['Start'], errors='coerce')

    # Séparation en colonnes Date et Time
    df['Time'] = df['Start'].dt.strftime('%H:%M:%S')
    df['Start'] = df['Start'].dt.strftime('%Y-%m-%d')  

    # Colonnes optionnelles d'analyse
    df['Jour_semaine'] = pd.to_datetime(df['Start']).dt.day_name()
    df['Mois'] = pd.to_datetime(df['Start']).dt.month
    df['Heure (h)'] = pd.to_datetime(df['Time'], format='%H:%M:%S').dt.hour

    # Statistiques affichées
    print(f"--- {nom} ---")
    print("Dates min :", df['Start'].min())
    print("Dates max :", df['Start'].max())
    print("Nb dates manquantes :", df['Start'].isna().sum())
    print("Répartition par mois :\n", df['Mois'].value_counts().sort_index())
    print()

    return df

In [19]:
Apr24_clean=analyser_dates(Apr24,"Apr24")

--- Apr24 ---
Dates min : 2024-04-01
Dates max : 2024-05-02
Nb dates manquantes : 0
Répartition par mois :
 Mois
4    126300
5      3333
Name: count, dtype: int64

In [20]:
Apr24_clean

,CPID,Amount,Consumed(kWh),Start,Duration,Time,Jour_semaine,Mois,Heure (h)
0,UC25189,10.99,19.99,2024-04-08,00:30:53,00:54:38,Monday,4,0
1,61720,4.86,17.99,2024-04-08,00:23:42,00:53:19,Monday,4,0
2,UC25188,1.04,1.88,2024-04-08,00:19:48,00:51:29,Monday,4,0
3,APT51423,15.56,30.35,2024-04-08,00:47:21,00:51:08,Monday,4,0
4,52993,20.02,57.19,2024-04-08,10:01:30,00:49:38,Monday,4,0
...,...,...,...,...,...,...,...,...,...
129628,APT51423,11.65,22.54,2024-04-29,00:32:06,01:48:24,Monday,4,1
129629,51514,1.85,3.37,2024-04-29,00:18:17,01:45:19,Monday,4,1
129630,FC15744,0.00,0.48,2024-04-29,10:58:55,01:41:06,Monday,4,1
129631,APT50455,5.46,25.74,2024-04-29,05:28:56,01:37:29,Monday,4,1
129632,APT51423,6.25,11.74,2024-04-29,00:17:44,01:07:26,Monday,4,1

In [21]:

Apr24_clean=Apr24_clean[['CPID', 'Amount', 'Consumed(kWh)', 'Duration', 'Start', 'Time']]

In [22]:
Apr24_clean.to_excel("Apr24_clean.xlsx",index=False)

In [204]:
chemin24 = "fichierbrutsexcel/2024"

Jul24 = pd.read_excel(os.path.join(chemin24, '7.xlsx'))
Jul24

,Site,CPID,Connector type,Connector ID,CURR,Amt,CONSUM,Duration,start time
0,"X Leisure, Fountain Park Centre, Edinburgh",APT50793,type_2_plug,2,gbp,0.00,9.778,02:43:33,2024-07-01 18:19:52
1,Hopehill Road,61707,type_2_plug,1,gbp,8.93,19.819,02:48:18,2024-07-01 18:18:09
2,Virginia Street Car Park,61918,ccs,1,gbp,10.39,22.117,00:29:55,2024-07-01 20:34:00
3,"X Leisure, Fountain Park Centre, Edinburgh",APT50793,type_2_plug,1,gbp,0.00,14.749,01:39:27,2024-07-01 19:31:56
4,Halbeath Park and Ride,60489,ccs,1,gbp,4.64,20.290,00:24:52,2024-07-01 17:36:05
...,...,...,...,...,...,...,...,...,...
135098,"Ladyhill Road, Elgin",APT51303,ccs,1,gbp,10.97,19.597,00:34:47,2024-07-24 05:36:32
135099,Blairtummoch Road,62878,type_2_plug,2,gbp,0.00,27.427,14:48:03,2024-07-23 16:11:04
135100,"Cluny Place Car Park, Buckie",54242,ccs,1,gbp,26.45,47.231,01:15:40,2024-07-24 05:52:51
135101,"Schuh, Deans Industrial Estate, Livingston",4534,type_2_plug,1,gbp,NaN,NaN,00:00:02,2024-07-24 07:13:55
135102,"Smith Street Car Park, Dalry",53244,ccs,1,gbp,20.15,54.453,01:52:16,2024-07-24 05:29:10

In [207]:
# Sélectionner les colonnes que tu veux garder
cols_to_keep = ['CPID','Amt','CONSUM','start time','Duration']
Jul24=Jul24[cols_to_keep]

# Renommer les colonnes spécifiées
Jul24=Jul24.rename(columns={
'CONSUM': 'Consumed(kWh)',
'Amt':'Amount',
'start time':'Start'
})
Jul24

            CPID  Amount  Consumed(kWh)               Start  Duration
0       APT50793    0.00          9.778 2024-07-01 18:19:52  02:43:33
1          61707    8.93         19.819 2024-07-01 18:18:09  02:48:18
2          61918   10.39         22.117 2024-07-01 20:34:00  00:29:55
3       APT50793    0.00         14.749 2024-07-01 19:31:56  01:39:27
4          60489    4.64         20.290 2024-07-01 17:36:05  00:24:52
...          ...     ...            ...                 ...       ...
135098  APT51303   10.97         19.597 2024-07-24 05:36:32  00:34:47
135099     62878    0.00         27.427 2024-07-23 16:11:04  14:48:03
135100     54242   26.45         47.231 2024-07-24 05:52:51  01:15:40
135101      4534     NaN            NaN 2024-07-24 07:13:55  00:00:02
135102     53244   20.15         54.453 2024-07-24 05:29:10  01:52:16

[135103 rows x 5 columns]

In [208]:

# Fonction de traitement
def analyser_dates(df, nom):
    df = df.copy()

    # Conversion CPID en string
    df['CPID'] = df['CPID'].astype(str)

    # Conversion de Start en datetime
    df['Start'] = pd.to_datetime(df['Start'], errors='coerce')

    # Séparation en colonnes Date et Time
    df['Time'] = df['Start'].dt.strftime('%H:%M:%S')
    df['Start'] = df['Start'].dt.strftime('%Y-%m-%d')  

    # Colonnes optionnelles d'analyse
    df['Jour_semaine'] = pd.to_datetime(df['Start']).dt.day_name()
    df['Mois'] = pd.to_datetime(df['Start']).dt.month
    df['Heure (h)'] = pd.to_datetime(df['Time'], format='%H:%M:%S').dt.hour

    # Statistiques affichées
    print(f"--- {nom} ---")
    print("Dates min :", df['Start'].min())
    print("Dates max :", df['Start'].max())
    print("Nb dates manquantes :", df['Start'].isna().sum())
    print("Répartition par mois :\n", df['Mois'].value_counts().sort_index())
    print()

    return df

In [209]:
Jul24_clean=analyser_dates(Jul24,"Jul24")

--- Jul24 ---
Dates min : 2024-07-01
Dates max : 2024-08-01
Nb dates manquantes : 0
Répartition par mois :
 Mois
7    135093
8        10
Name: count, dtype: int64

In [210]:
Jul24_clean

,CPID,Amount,Consumed(kWh),Start,Duration,Time,Jour_semaine,Mois,Heure (h)
0,APT50793,0.00,9.778,2024-07-01,02:43:33,18:19:52,Monday,7,18
1,61707,8.93,19.819,2024-07-01,02:48:18,18:18:09,Monday,7,18
2,61918,10.39,22.117,2024-07-01,00:29:55,20:34:00,Monday,7,20
3,APT50793,0.00,14.749,2024-07-01,01:39:27,19:31:56,Monday,7,19
4,60489,4.64,20.290,2024-07-01,00:24:52,17:36:05,Monday,7,17
...,...,...,...,...,...,...,...,...,...
135098,APT51303,10.97,19.597,2024-07-24,00:34:47,05:36:32,Wednesday,7,5
135099,62878,0.00,27.427,2024-07-23,14:48:03,16:11:04,Tuesday,7,16
135100,54242,26.45,47.231,2024-07-24,01:15:40,05:52:51,Wednesday,7,5
135101,4534,NaN,NaN,2024-07-24,00:00:02,07:13:55,Wednesday,7,7
135102,53244,20.15,54.453,2024-07-24,01:52:16,05:29:10,Wednesday,7,5

In [211]:

Jul24_clean=Jul24_clean[['CPID', 'Amount', 'Consumed(kWh)', 'Duration', 'Start', 'Time']]

In [194]:
May24_clean

,CPID,Amount,Consumed(kWh),Duration,Start,Time
0,51567,13.06,17.23,00:27:37,2024-05-06,00:56:27
1,52338,8.74,21.85,10:16:05,2024-05-06,00:55:14
2,51550,5.65,10.55,00:23:00,2024-05-06,00:54:44
3,52679,16.24,36.08,11:21:15,2024-05-06,00:49:56
4,T53-2915-005,0.00,35.13,00:48:37,2024-05-06,00:48:56
...,...,...,...,...,...,...
113981,t54_hu1_3919_016,10.38,17.30,00:30:19,2024-05-31,01:19:36
113982,FC16570,10.82,21.65,01:58:19,2024-05-31,01:16:19
113983,51564,0.00,18.53,00:51:04,2024-05-31,01:05:22
113984,61196,9.61,19.22,00:54:51,2024-05-31,01:00:43
113985,50795,0.00,16.89,01:24:40,2024-05-31,01:00:14

In [213]:

Jul24_clean.to_excel("Jul24_clean.xlsx",index=False)

In [90]:
Sep24.head()

   Amount  Duration               Start
0    6.19    1113.0 2024-09-01 01:00:39
1    0.00   25187.0 2024-09-01 01:03:24
2    6.14     881.0 2024-09-01 01:03:55
3   27.79    3759.0 2024-09-01 01:05:28
4   13.48    1611.0 2024-09-01 01:12:03

In [74]:
def analyser_dates(df, nom):
    df = df.copy()

    df['CPID'] = df['CPID'].astype(str)

    df['Start'] = pd.to_datetime(df['Start'], dayfirst=True, errors='coerce')

    def extraire_heure_avec_secondes(dt):
        if pd.isna(dt):
            return None
        # Extraire hh:mm puis ajouter :00 secondes
        return dt.strftime('%H:%M') + ':00'

    df['Time'] = df['Start'].apply(extraire_heure_avec_secondes)
    df['Start'] = df['Start'].dt.strftime('%Y-%m-%d')

    print(f"--- {nom} ---")
    print("Dates min :", df['Start'].min())
    print("Dates max :", df['Start'].max())
    print("Nb dates manquantes :", df['Start'].isna().sum())
    print()

    return df

In [41]:
import os
import pandas as pd



# Fonction de traitement
def analyser_dates(df, nom):
    df = df.copy()

    # Conversion CPID en string
    df['CPID'] = df['CPID'].astype(str)

    # Conversion de Start en datetime
    df['Start'] = pd.to_datetime(df['Start'], dayfirst=True, errors='coerce')

    # Séparation en colonnes Date et Time
    df['Time'] = df['Start'].dt.strftime('%H:%M:%S')
    df['Start'] = df['Start'].dt.strftime('%Y-%m-%d')  

    # Colonnes optionnelles d'analyse
    df['Jour_semaine'] = pd.to_datetime(df['Start']).dt.day_name()
    df['Mois'] = pd.to_datetime(df['Start']).dt.month
    df['Heure (h)'] = pd.to_datetime(df['Time'], format='%H:%M:%S').dt.hour

    # Statistiques affichées
    print(f"--- {nom} ---")
    print("Dates min :", df['Start'].min())
    print("Dates max :", df['Start'].max())
    print("Nb dates manquantes :", df['Start'].isna().sum())
    print("Répartition par mois :\n", df['Mois'].value_counts().sort_index())
    print()

    return df

In [43]:
print(Aug24.columns)

Index(['Amount', 'Duration', 'Start'], dtype='object')

In [44]:

oct24_clean = analyser_dates(Oct24, "Octobre 2024")
dec24_clean = analyser_dates(Dec24, "Décembre 2024")

oct24_clean.to_excel("cleaned_oct24.xlsx", index=False)
dec24_clean.to_excel("cleaned_dec24.xlsx", index=False)

--- Octobre 2024 ---
Dates min : 2024-09-30
Dates max : 2024-10-31
Nb dates manquantes : 0
Répartition par mois :
 Mois
9         28
10    145435
Name: count, dtype: int64

--- Décembre 2024 ---
Dates min : 2024-12-01
Dates max : 2024-12-31
Nb dates manquantes : 0
Répartition par mois :
 Mois
12    142778
Name: count, dtype: int64

In [ ]:
chemin24 = "fichierbrutsexcel/2024"
Aug24 = pd.read_excel(os.path.join(chemin24, '8.xlsx'))

In [46]:
# Afficher les colonnes du fichier '8.xlsx'
print("Colonnes du fichier Aug24 (8.xlsx) :")
print(Aug24.columns)

# Afficher les colonnes du fichier '6.xlsx'
print("Colonnes du fichier Jun24 (6.xlsx) :")
print(Jun24.columns)

Colonnes du fichier Aug24 (8.xlsx) :
Index(['SITE', 'Display Id', 'Connector Type', 'Connecto id', 'Currency',
       'Amount', 'Consum', 'Duration', 'Start'],
      dtype='object')
Colonnes du fichier Jun24 (6.xlsx) :
Index(['Site', 'CP ID', 'Connector Type', 'Connector ID', 'Currency', 'Amount',
       'Consum', 'Duration', 'starttime'],
      dtype='object')

In [47]:
# Sélectionner les colonnes que tu veux garder
cols_to_keep = ['Display Id', 'Amount', 'Consum', 'Duration', 'Start']
Aug24 = Aug24[cols_to_keep]

# Renommer les colonnes spécifiées
Aug24 = Aug24.rename(columns={
    'Display Id': 'CPID',
    'Consum': 'Consumed(kWh)'
})

# Afficher le résultat pour vérifier
print(Aug24.head())

    CPID  Amount  Consumed(kWh)  Duration             Start
0  62325   17.56         35.119  00:50:48  19/08/2024 01:31
1  61099   17.81         30.700  01:13:34  19/08/2024 01:35
2  60228   23.49         56.220  11:50:49  18/08/2024 19:23
3  60117    7.01         23.379  01:19:37  19/08/2024 05:54
4  61099    5.85         10.086  00:12:23  19/08/2024 07:04

In [48]:
# Convertir la colonne 'Start' en datetime
Aug24['Start'] = pd.to_datetime(Aug24['Start'], dayfirst=True)  # dayfirst=True car format jj/mm/yyyy

# Créer la colonne 'Time' qui contient l'heure au format hh:mm:ss
Aug24['Time'] = Aug24['Start'].dt.time.astype(str)

# Modifier la colonne 'Start' pour ne garder que la date au format yyyy-mm-dd
Aug24['Start'] = Aug24['Start'].dt.date.astype(str)

# Convertir CPID en chaîne de caractères
Aug24['CPID'] = Aug24['CPID'].astype(str)

# Afficher le résultat
print(Aug24.head())

    CPID  Amount  Consumed(kWh)  Duration       Start      Time
0  62325   17.56         35.119  00:50:48  2024-08-19  01:31:00
1  61099   17.81         30.700  01:13:34  2024-08-19  01:35:00
2  60228   23.49         56.220  11:50:49  2024-08-18  19:23:00
3  60117    7.01         23.379  01:19:37  2024-08-19  05:54:00
4  61099    5.85         10.086  00:12:23  2024-08-19  07:04:00

In [52]:
import os

chemin24_output = "fichiersexceluniformises/2024"

# S'assurer que le dossier existe (le crée sinon)
os.makedirs(chemin24_output, exist_ok=True)

# Enregistrer le DataFrame dans le fichier Excel
Aug24.to_excel(os.path.join(chemin24_output, '8.xlsx'), index=False)

In [53]:
chemin24_output = "fichiersexceluniformises/2024"
Aug24 = pd.read_excel(os.path.join(chemin24_output, '8.xlsx'))

In [54]:
Aug24.head()

    CPID  Amount  Consumed(kWh)  Duration       Start      Time
0  62325   17.56         35.119  00:50:48  2024-08-19  01:31:00
1  61099   17.81         30.700  01:13:34  2024-08-19  01:35:00
2  60228   23.49         56.220  11:50:49  2024-08-18  19:23:00
3  60117    7.01         23.379  01:19:37  2024-08-19  05:54:00
4  61099    5.85         10.086  00:12:23  2024-08-19  07:04:00

In [64]:
chemin24 = "fichierbrutsexcel/2024"
Jun24 = pd.read_excel(os.path.join(chemin24, '6.xlsx'))

In [66]:
Jun24.head()

,Site,CP ID,Connector Type,Connector ID,Currency,Amount,Consum,Duration,starttime
0,Mill Street,62916,Rapid,2,gbp,1.45,2.892,00:42:32,2024-06-01 10:44:16
1,Council Car Park,61917,Slow,2,gbp,0.00,0.570,00:07:00,2024-06-01 11:15:02
2,Bayfield Car Park,61778,Rapid,3,gbp,0.00,0.840,00:15:31,2024-06-01 11:15:21
3,Broadwood Stadium,53579,Rapid,1,gbp,32.20,46.004,01:02:10,2024-06-01 10:25:39
4,"Station Road Car Park, Strathaven",54022,Fast,2,gbp,2.47,6.172,00:57:35,2024-06-01 10:38:49

In [67]:
# Colonnes à garder
cols_to_keep_jun = ['CP ID', 'Amount', 'Consum', 'Duration', 'starttime']

# Sélectionner uniquement ces colonnes
Jun24 = Jun24[cols_to_keep_jun]

# Renommer les colonnes
Jun24 = Jun24.rename(columns={
    'CP ID': 'CPID',
    'Consum': 'Consumed(kWh)',
    'starttime': 'Start'
})

# Vérifier le résultat
print(Jun24.head())

    CPID  Amount  Consumed(kWh)  Duration               Start
0  62916    1.45          2.892  00:42:32 2024-06-01 10:44:16
1  61917    0.00          0.570  00:07:00 2024-06-01 11:15:02
2  61778    0.00          0.840  00:15:31 2024-06-01 11:15:21
3  53579   32.20         46.004  01:02:10 2024-06-01 10:25:39
4  54022    2.47          6.172  00:57:35 2024-06-01 10:38:49

In [68]:
# Convertir 'Start' en datetime
Jun24['Start'] = pd.to_datetime(Jun24['Start'])

# Extraire l'heure au format hh:mm:ss et la mettre dans une nouvelle colonne 'Time'
Jun24['Time'] = Jun24['Start'].dt.strftime('%H:%M:%S')

# Extraire uniquement la date (yyyy-mm-dd) dans la colonne 'Start'
Jun24['Start'] = Jun24['Start'].dt.date.astype(str)

# Convertir CPID en chaîne de caractères
Jun24['CPID'] = Jun24['CPID'].astype(str)

# Vérifier le résultat
print(Jun24.head())

    CPID  Amount  Consumed(kWh)  Duration       Start      Time
0  62916    1.45          2.892  00:42:32  2024-06-01  10:44:16
1  61917    0.00          0.570  00:07:00  2024-06-01  11:15:02
2  61778    0.00          0.840  00:15:31  2024-06-01  11:15:21
3  53579   32.20         46.004  01:02:10  2024-06-01  10:25:39
4  54022    2.47          6.172  00:57:35  2024-06-01  10:38:49

In [ ]:
chemin24_output = "fichiersexceluniformises/2024"
# Créer le dossier s'il n'existe pas
os.makedirs(chemin24_output, exist_ok=True)
# Enregistrer Jun24 dans le fichier Excel
Jun24.to_excel(os.path.join(chemin24_output, '6.xlsx'), index=False)

In [95]:
chemin24 = "fichierbrutsexcel/2024"
Sep24 = pd.read_excel(os.path.join(chemin24, '9.xlsx'))

In [97]:
Sep24.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111513 entries, 0 to 111512
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   SITE         111479 non-null  object
 1   Display Id   111513 non-null  object
 2   Connecto id  111513 non-null  int64
 3   Currency     111513 non-null  object
 4   Amount       111513 non-null  float64
 5   Consum       110458 non-null  float64
 6   Duration     111501 non-null  float64
 7   Start        111513 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 6.8+ MB

In [98]:
print(Sep24.columns)

Index(['SITE', 'Display Id', 'Connecto id', 'Currency', 'Amount', 'Consum',
       'Duration', 'Start'],
      dtype='object')

In [99]:
# Colonnes à garder
cols_to_keep_sep = ['Display Id', 'Amount', 'Consum', 'Duration', 'Start']

# Sélectionner uniquement ces colonnes
Sep24 = Sep24[cols_to_keep_sep]

# Renommer les colonnes
Sep24 = Sep24.rename(columns={
    'Display Id': 'CPID',
    'Consum': 'Consumed(kWh)'
})

# Vérifier le résultat
print(Sep24.head())

    CPID  Amount  Consumed(kWh)  Duration               Start
0  60614    6.19         11.261    1113.0 2024-09-01 01:00:39
1  51301    0.00         52.782   25187.0 2024-09-01 01:03:24
2  51423    6.14         10.468     881.0 2024-09-01 01:03:55
3  61612   27.79         49.829    3759.0 2024-09-01 01:05:28
4  53525   13.48         22.852    1611.0 2024-09-01 01:12:03

In [102]:
def analyser_dates_sep(df, nom):
    df = df.copy()

    df['CPID'] = df['CPID'].astype(str)
    df['Start'] = pd.to_datetime(df['Start'], errors='coerce')

    df['Date'] = df['Start'].dt.strftime('%Y-%m-%d')
    df['Time'] = df['Start'].dt.strftime('%H:%M:%S')

    # Supprimer la colonne Start d'origine
    df = df.drop(columns=['Start'])

    # Renommer Date en Start
    df = df.rename(columns={'Date': 'Start'})

    print(f"--- {nom} ---")
    print("Dates min :", df['Start'].min())
    print("Dates max :", df['Start'].max())
    print("Nb dates manquantes :", df['Start'].isna().sum())
    print()

    return df

In [ ]:
Sep24_processed = analyser_dates_sep(Sep24, "Sep24")
print(Sep24_processed.head())

--- Sep24 ---
Dates min : 2024-09-01
Dates max : 2024-10-01
Nb dates manquantes : 0

    CPID  Amount  Consumed(kWh)  Duration       Start      Time
0  60614    6.19         11.261    1113.0  2024-09-01  01:00:39
1  51301    0.00         52.782   25187.0  2024-09-01  01:03:24
2  51423    6.14         10.468     881.0  2024-09-01  01:03:55
3  61612   27.79         49.829    3759.0  2024-09-01  01:05:28
4  53525   13.48         22.852    1611.0  2024-09-01  01:12:03

In [104]:
chemin24_output = "fichiersexceluniformises/2024"
Sep24_processed.to_excel(os.path.join(chemin24_output, '9.xlsx'), index=False)

In [ ]:
Oct24 = pd.read_excel(os.path.join(chemin24_output, '10.xlsx'))

In [117]:
Oct24.head(10000)

      Amount   CPID  Consumed(kWh)  Duration             Start
0       5.00  52042          9.299  00:22:18  31/10/2024 23:59
1       3.29  60148          5.723  00:29:20  31/10/2024 23:56
2       4.28  53034          8.558  00:12:04  31/10/2024 23:53
3       9.39  52316         30.029  08:38:14  31/10/2024 23:51
4       0.00  52746         23.847  00:39:19  31/10/2024 23:50
...      ...    ...            ...       ...               ...
9995    0.00  51161          8.500  08:12:03  30/10/2024 07:18
9996    7.23  52473         19.547  00:23:05  30/10/2024 07:17
9997   61.47  52650         15.295  02:09:24  30/10/2024 07:17
9998    0.00  11216            NaN  00:00:01  30/10/2024 07:17
9999   13.92  60875         18.557  00:49:23  30/10/2024 07:17

[10000 rows x 5 columns]

In [118]:
def analyser_dates_oct(df, nom):
    df = df.copy()

    df['CPID'] = df['CPID'].astype(str)

    df['Start'] = pd.to_datetime(df['Start'], dayfirst=True, errors='coerce')


    df['Date'] = df['Start'].dt.strftime('%Y-%m-%d')

    df['Time'] = df['Start'].dt.strftime('%H:%M:%S')

    df = df.drop(columns=['Start'])


    df = df.rename(columns={'Date': 'Start'})

    print(f"--- {nom} ---")
    print("Dates min :", df['Start'].min())
    print("Dates max :", df['Start'].max())
    print("Nb dates manquantes :", df['Start'].isna().sum())
    print()

    return df

In [119]:
Oct24_processed = analyser_dates_oct(Oct24, "Oct24")

--- Oct24 ---
Dates min : 2024-09-30
Dates max : 2024-10-31
Nb dates manquantes : 0

In [120]:
Oct24_processed.head()

   Amount   CPID  Consumed(kWh)  Duration       Start      Time
0    5.00  52042          9.299  00:22:18  2024-10-31  23:59:00
1    3.29  60148          5.723  00:29:20  2024-10-31  23:56:00
2    4.28  53034          8.558  00:12:04  2024-10-31  23:53:00
3    9.39  52316         30.029  08:38:14  2024-10-31  23:51:00
4    0.00  52746         23.847  00:39:19  2024-10-31  23:50:00

In [121]:
chemin24_output = "fichiersexceluniformises/2024"
Oct24_processed.to_excel(os.path.join(chemin24_output, '10.xlsx'), index=False)

In [ ]:
Nov24 = pd.read_excel(os.path.join(chemin24_output, '11.xlsx'))

In [122]:
Nov24.head()

   Amount      CPID  Consumed(kWh)  Duration             Start
0    0.00  APT51549         15.695  00:54:19  30/11/2024 23:59
1   15.04     60452         37.590  05:59:01  30/11/2024 23:56
2   21.39     52973         57.802  01:54:26  30/11/2024 23:55
3    0.00  APT51160          7.793  02:14:59  30/11/2024 23:53
4    2.26     52305          5.012  00:11:52  30/11/2024 23:51

In [123]:
def analyser_dates_nov(df, nom):
    df = df.copy()

    df['CPID'] = df['CPID'].astype(str)

    df['Start'] = pd.to_datetime(df['Start'], dayfirst=True, errors='coerce')


    df['Date'] = df['Start'].dt.strftime('%Y-%m-%d')

    df['Time'] = df['Start'].dt.strftime('%H:%M:%S')

    df = df.drop(columns=['Start'])


    df = df.rename(columns={'Date': 'Start'})

    print(f"--- {nom} ---")
    print("Dates min :", df['Start'].min())
    print("Dates max :", df['Start'].max())
    print("Nb dates manquantes :", df['Start'].isna().sum())
    print()

    return df

In [124]:
Nov24_processed = analyser_dates_nov(Nov24, "Nov24")

--- Nov24 ---
Dates min : 2024-11-01
Dates max : 2024-11-30
Nb dates manquantes : 0

In [126]:
Nov24_processed.head()

   Amount      CPID  Consumed(kWh)  Duration       Start      Time
0    0.00  APT51549         15.695  00:54:19  2024-11-30  23:59:00
1   15.04     60452         37.590  05:59:01  2024-11-30  23:56:00
2   21.39     52973         57.802  01:54:26  2024-11-30  23:55:00
3    0.00  APT51160          7.793  02:14:59  2024-11-30  23:53:00
4    2.26     52305          5.012  00:11:52  2024-11-30  23:51:00

In [127]:
chemin24_output = "fichiersexceluniformises/2024"
Nov24_processed.to_excel(os.path.join(chemin24_output, '11.xlsx'), index=False)

In [128]:
Dec24 = pd.read_excel(os.path.join(chemin24_output, '12.xlsx'))

In [129]:
Dec24.head()

   Amount      CPID  Consumed(kWh)  Duration             Start
0    0.00  APT50661         50.089  10:28:41  31/12/2024 23:58
1    7.87     51429         13.612  00:24:38  31/12/2024 23:55
2    7.38     51548         12.720  00:18:12  31/12/2024 23:55
3   10.23     51564         17.058  00:20:37  31/12/2024 23:53
4   14.73     51426         26.098  00:41:33  31/12/2024 23:51

In [ ]:
def analyser_dates_dec(df, nom):
    df = df.copy()

    df['CPID'] = df['CPID'].astype(str)

    df['Start'] = pd.to_datetime(df['Start'], dayfirst=True, errors='coerce')


    df['Date'] = df['Start'].dt.strftime('%Y-%m-%d')

    df['Time'] = df['Start'].dt.strftime('%H:%M:%S')

    df = df.drop(columns=['Start'])


    df = df.rename(columns={'Date': 'Start'})

    print(f"--- {nom} ---")
    print("Dates min :", df['Start'].min())
    print("Dates max :", df['Start'].max())
    print("Nb dates manquantes :", df['Start'].isna().sum())
    print()

    return df

In [133]:
Dec24_processed = analyser_dates_dec(Dec24, "Dec24")

--- Dec24 ---
Dates min : 2024-12-01
Dates max : 2024-12-31
Nb dates manquantes : 0

In [134]:
Dec24_processed.head()

   Amount      CPID  Consumed(kWh)  Duration       Start      Time
0    0.00  APT50661         50.089  10:28:41  2024-12-31  23:58:00
1    7.87     51429         13.612  00:24:38  2024-12-31  23:55:00
2    7.38     51548         12.720  00:18:12  2024-12-31  23:55:00
3   10.23     51564         17.058  00:20:37  2024-12-31  23:53:00
4   14.73     51426         26.098  00:41:33  2024-12-31  23:51:00

In [ ]:
chemin24_output = "fichiersexceluniformises/2024"
Dec24_processed.to_excel(os.path.join(chemin24_output, '12.xlsx'), index=False)

Exception ignored in: <bound method IPythonKernel._clean_thread_parent_frames of <ipykernel.ipkernel.IPythonKernel object at 0x000001E37E055130>>
Traceback (most recent call last):
  File "C:\Users\C52685\AppData\Roaming\Python\Python312\site-packages\ipykernel\ipkernel.py", line 790, in _clean_thread_parent_frames
    active_threads = {thread.ident for thread in threading.enumerate()}
                                                 ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\C52685\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1513, in enumerate
    def enumerate():

KeyboardInterrupt:

In [147]:
Dec24 = pd.read_excel(os.path.join(chemin24_output, '12.xlsx'))

In [148]:
Dec24.head()

   Amount      CPID  Consumed(kWh)  Duration       Start      Time
0    0.00  APT50661         50.089  10:28:41  2024-12-31  23:58:00
1    7.87     51429         13.612  00:24:38  2024-12-31  23:55:00
2    7.38     51548         12.720  00:18:12  2024-12-31  23:55:00
3   10.23     51564         17.058  00:20:37  2024-12-31  23:53:00
4   14.73     51426         26.098  00:41:33  2024-12-31  23:51:00

In [149]:
chemin25="fichiersexceluniformises/2025"

In [ ]:
Jan25 = pd.read_excel(os.path.join(chemin25, '1.xlsx'))

In [152]:
Jan25.head()

   Amount   CPID  Consumed(kWh)  Duration             Start
0    0.00  54084         41.762  09:18:59  31/01/2025 23:59
1   25.24  60682         45.209  00:57:16  31/01/2025 23:58
2   14.39  51595         25.472  00:35:45  31/01/2025 23:54
3   22.34  51678         44.679  01:10:00  31/01/2025 23:53
4    5.00  51501         10.000  00:25:08  31/01/2025 23:51

In [153]:
def analyser_dates_jan(df, nom):
    df = df.copy()

    df['CPID'] = df['CPID'].astype(str)

    df['Start'] = pd.to_datetime(df['Start'], dayfirst=True, errors='coerce')


    df['Date'] = df['Start'].dt.strftime('%Y-%m-%d')

    df['Time'] = df['Start'].dt.strftime('%H:%M:%S')

    df = df.drop(columns=['Start'])


    df = df.rename(columns={'Date': 'Start'})

    print(f"--- {nom} ---")
    print("Dates min :", df['Start'].min())
    print("Dates max :", df['Start'].max())
    print("Nb dates manquantes :", df['Start'].isna().sum())
    print()

    return df

In [ ]:
Jan25_processed = analyser_dates_jan(Jan25, "Jan25")

--- Jan25 ---
Dates min : 2025-01-01
Dates max : 2025-01-31
Nb dates manquantes : 0

In [155]:
Jan25_processed.head()

   Amount   CPID  Consumed(kWh)  Duration       Start      Time
0    0.00  54084         41.762  09:18:59  2025-01-31  23:59:00
1   25.24  60682         45.209  00:57:16  2025-01-31  23:58:00
2   14.39  51595         25.472  00:35:45  2025-01-31  23:54:00
3   22.34  51678         44.679  01:10:00  2025-01-31  23:53:00
4    5.00  51501         10.000  00:25:08  2025-01-31  23:51:00

In [156]:
chemin25_output = "fichiersexceluniformises/2025"
Jan25_processed.to_excel(os.path.join(chemin25_output, '1.xlsx'), index=False)

In [ ]:
Feb25 = pd.read_excel(os.path.join(chemin25, '2.xlsx'))

In [157]:
Feb25.head()

   Amount      CPID  Consumed(kWh)  Duration             Start
0   12.36     60601         30.889  09:43:13  28/02/2025 23:59
1    0.00  APT51160         23.400  02:16:26  28/02/2025 23:55
2   25.87     52708         62.180  09:29:10  28/02/2025 23:52
3    0.00     50954         14.898  01:29:08  28/02/2025 23:51
4   30.55     61631         59.099  07:44:36  28/02/2025 23:50

In [158]:
def analyser_dates_feb(df, nom):
    df = df.copy()

    df['CPID'] = df['CPID'].astype(str)

    df['Start'] = pd.to_datetime(df['Start'], dayfirst=True, errors='coerce')


    df['Date'] = df['Start'].dt.strftime('%Y-%m-%d')

    df['Time'] = df['Start'].dt.strftime('%H:%M:%S')

    df = df.drop(columns=['Start'])


    df = df.rename(columns={'Date': 'Start'})

    print(f"--- {nom} ---")
    print("Dates min :", df['Start'].min())
    print("Dates max :", df['Start'].max())
    print("Nb dates manquantes :", df['Start'].isna().sum())
    print()

    return df

In [160]:
Feb25_processed = analyser_dates_feb(Feb25, "Feb25")

--- Feb25 ---
Dates min : 2025-02-01
Dates max : 2025-02-28
Nb dates manquantes : 0

In [162]:
Feb25_processed.head()

   Amount      CPID  Consumed(kWh)  Duration       Start      Time
0   12.36     60601         30.889  09:43:13  2025-02-28  23:59:00
1    0.00  APT51160         23.400  02:16:26  2025-02-28  23:55:00
2   25.87     52708         62.180  09:29:10  2025-02-28  23:52:00
3    0.00     50954         14.898  01:29:08  2025-02-28  23:51:00
4   30.55     61631         59.099  07:44:36  2025-02-28  23:50:00

In [163]:
chemin25_output = "fichiersexceluniformises/2025"
Feb25_processed.to_excel(os.path.join(chemin25_output, '2.xlsx'), index=False)

In [ ]:
Apr25 = pd.read_excel(os.path.join(chemin25, '4.xlsx'))

In [164]:
Apr25.head()

   Amount   CPID  Consumed(kWh)  Duration             Start
0    0.00  60275         56.586  01:21:28  30/04/2025 23:58
1   13.26  51498         30.660  00:53:27  30/04/2025 23:57
2   24.36  61615         43.606  01:11:18  30/04/2025 23:56
3    4.99  62525         10.623  00:20:42  30/04/2025 23:54
4   24.13  61624         53.620  08:15:39  30/04/2025 23:51

In [165]:
def analyser_dates_apr(df, nom):
    df = df.copy()

    df['CPID'] = df['CPID'].astype(str)

    df['Start'] = pd.to_datetime(df['Start'], dayfirst=True, errors='coerce')


    df['Date'] = df['Start'].dt.strftime('%Y-%m-%d')

    df['Time'] = df['Start'].dt.strftime('%H:%M:%S')

    df = df.drop(columns=['Start'])


    df = df.rename(columns={'Date': 'Start'})

    print(f"--- {nom} ---")
    print("Dates min :", df['Start'].min())
    print("Dates max :", df['Start'].max())
    print("Nb dates manquantes :", df['Start'].isna().sum())
    print()

    return df

In [167]:
Apr25_processed = analyser_dates_apr(Apr25, "Apr25")

--- Apr25 ---
Dates min : 2025-04-01
Dates max : 2025-04-30
Nb dates manquantes : 0

In [170]:
chemin25_output = "fichiersexceluniformises/2025"
Apr25_processed.to_excel(os.path.join(chemin25_output, '4.xlsx'), index=False)